Updates new deploy
kontent-ai/sample-app-preview-react pull request #5
Opened 2024-06-04 13:36 UTC by IvanKiral

### Motivation

Which issue does this fix? Fixes #`issue number`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2024-06-10 10:30 UTC, JiriLojda requested changes
You seem to have removed the deployment step from the CI but didn't add a replacement. How do you plan deploying the app?

2024-06-10 10:30 UTC, JiriLojda commented on src/constants/routePaths.ts
>  export type ProjectRouteParams = {
Since you are at it, you can as well rename the last few remaining references to the old name "project". I found this, "DeployedProjectRootRoute", and "ProductDetailsRouteParams". There are also `REACT_APP_PROJECT_DOMAIN` and `REACT_APP_PROJECT_ROUTE` environment variables, but keep in mind that changing those would  require changing the configuration of the deployment.

2024-06-10 10:30 UTC, JiriLojda commented on src/components/ErrorPage.tsx
> +const EnvironmentIdUrlTemplate = "https://getting-started.sample.kontent.ai/<your_project_id>";
Change also the placeholder in the url.

2024-06-10 10:30 UTC, JiriLojda commented on src/repositories/previewApiKeyRepository.ts
> +  return get(url, requestContext).then(async res => await res.json() as KeyFromSeedResponse);
The `async/await` feature is not needed in the `then` callback.

2024-06-10 10:30 UTC, JiriLojda commented on src/repositories/projectContainerRepository.ts
> +    .then(res => res?.projectContainerId ?? null);
Why did you decide to return just the id instead of the whole project container? It is less general than it was. Anyway, if you want to return just the id, you should change the name of the function.

2024-06-10 10:30 UTC, JiriLojda commented on package.json
> +    "dprint": "^0.46.1",
There is already a new patch version of dprint. You can as well update to it. 😄

2024-06-11 08:23 UTC, IvanKiral commented on src/constants/routePaths.ts
>  export type ProjectRouteParams = {
I don't think these refer to environments rather the React project and where it is deployed, therefore I felt them untouched

2024-06-11 08:23 UTC, IvanKiral commented on src/components/ErrorPage.tsx
> +const EnvironmentIdUrlTemplate = "https://getting-started.sample.kontent.ai/<your_project_id>";
good catch

2024-06-11 08:45 UTC, IvanKiral commented on src/repositories/projectContainerRepository.ts
> +    .then(res => res?.projectContainerId ?? null);
I got it back to returning whole project container

2024-06-11 08:47 UTC, IvanKiral commented on src/constants/routePaths.ts
>  export type ProjectRouteParams = {
`ProductDetailsRouteParams` this was probably a mistake? :) it is product not project

2024-06-11 09:07 UTC, JiriLojda approved these changes, later dismissed

2024-06-11 09:07 UTC, JiriLojda commented on package.json
>      "gh-pages": "^2.0.1"
I believe that we can remove this dependency now.

2024-06-11 09:08 UTC, JiriLojda commented
Would you also please add the devrel team into code owners so that my reviews here matter? 😄

2024-06-18 09:42 UTC, merged